package tests

option go_out "tests_out"
option string_size 64

service User {
    Hello([3]string): [3]string
    CreateUser(Crededentials): string
    VoidFunction: ()
    MultipleResults(): (First, Second, Third)
}

struct Crededentials {
    Username string
    Password string
    Admin bool
    Number float32
}
struct OtherStruct {
    Creds Crededentials
    ExampleValue string
    Array [20]int
}
struct First {
    Info OtherStruct
}
struct Second {
    Info First
}
struct Third {
    Info Second
}
