package users

option go_out "tests_out"
option string_size 64

service User {
    CreateUser(Crededentials, OtherStruct): string
    VoidFunction: nil
    MultipleResults(): (First, Second, Third)
}

struct Crededentials {
    Username string
    Password string
    Admin bool
    Number float32
}
struct OtherStruct {
    Creds Crededentials
    ExampleValue string
}
struct First {
    Info OtherStruct
}
struct Second {
    Info First
}
struct Third {
    Info Second
}
