package tests

option go_out "tests_out"

service Second {
    Hello([]string): ([]string)
    UberFunc(string, int, int8, int16, int32, int64, float32, float64, bool, [3]string, [3]int, [3]int8, [3]int16, [3]int32, [3]int64, [3]float32, [3]float64, [3]bool, [3]Uber): (string, int, int8, int16, int32, int64, float32, float64, bool, [3]string, [3]int, [3]int8, [3]int16, [3]int32, [3]int64, [3]float32, [3]float64, [3]bool, [3]Uber)
}
struct Uber3 {
    String string

    Int int
    Int8 int8
    Int16 int16
    Int32 int32
    Int64 int64
    Complex complex64

    Float32 float32
    Float64 float64

    Bool bool
}

struct Uber2 {
    String string

    Int int
    Int8 int8
    Int16 int16
    Int32 int32
    Int64 int64

    Float32 float32
    Float64 float64

    Bool bool
    StructArray [5]Uber3
}
struct Uber {
    String string

    Int int
    Int8 int8
    Int16 int16
    Int32 int32
    Int64 int64

    Float32 float32
    Float64 float64

    Bool bool


    StringArray [10]string

    IntArray [5]int
    Int8Array [5]int8
    Int16Array [5]int16
    Int32Array [5]int32
    Int64Array [5]int64

    Float32Array [5]float32
    Float64Array [5]float64

    BoolArray [5]bool

    Struct Uber2
    StructArray [5]Uber2
    DynamicArray []string
}
